kernel:
  # Choose your kernel
  image: khulnasoft-lab/kernel:4.14.19
  cmdline: "console=ttyS0"
  tar: none
init:
  - khulnasoft-lab/init:d899eee3560a40aa3b4bdd67b3bb82703714b2b9
  - khulnasoft-lab/runc:7c39a68490a12cde830e1922f171c451fb08e731
  - khulnasoft-lab/containerd:37e397ebfc6bd5d8e18695b121166ffd0cbfd9f0
  - khulnasoft-lab/kernel-perf:4.14.19
  - hvtest-local
onboot:
  - name: sysctl
    image: khulnasoft-lab/sysctl:v0.2
services:
  - name: rngd
    image: khulnasoft-lab/rngd:v0.2
  - name: getty
    image: khulnasoft-lab/getty:v0.2
    binds:
      - /usr/bin/perf:/usr/bin/perf
      - /usr/bin/sock_stress:/usr/bin/sock_stress
      - /usr/bin/hvbench:/usr/bin/hvbench
      - /usr/bin/hvecho:/usr/bin/hvecho
      - /usr/bin/hvstress:/usr/bin/hvstress
      - /tmp:/tmp
      - /etc:/hostroot/etc
      - /var/log:/var/log
      - /dev:/dev
      - /sys:/sys
    env:
      - INSECURE=true
trust:
  org:
    - khulnasoft-lab
